name: deploy-frontend

on:
  push:
    branches: ["master"]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node (opcional si no hay dependencias)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/users-mysql-frontend:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/users-mysql-frontend:${{ github.sha }}
