name: deploy-frontend

on:
  push:
    branches: ["master"]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node (opcional)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build image with SHA tag
        run: docker build -t ${{ secrets.DOCKER_USER }}/users-mysql-frontend:${{ github.sha }} .

      - name: Tag image as latest
        run: docker tag ${{ secrets.DOCKER_USER }}/users-mysql-frontend:${{ github.sha }} ${{ secrets.DOCKER_USER }}/users-mysql-frontend:latest

      - name: Push both tags
        run: |
          docker push ${{ secrets.DOCKER_USER }}/users-mysql-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/users-mysql-frontend:latest
